README.md
applications/research-template.md

Clarification on the disburse of the grant

---

applications/leaderless_bft_consensus.md

added leaderless bft consensus

---

applications/leaderless_bft_consensus.md

changed payment address

---

applications/village-protocol.md

Village Protocol application submission

---

milestone-delivery/deliveries/Map_of_VeChain_Governance-Milestone_1.md

Map_of_VeChain_Governance-Milestone_1.md

---

applications/digital-village.md

Updated wallet address for Digital Village application

---

applications/village-protocol.md

Updated wallet address for Village Protocol application

---

applications/docs-internationalization.md

Docs internationalization grant application

---

applications/veRocket.md

Hi, sorry to bother you, we are upgrading our brand name, hence we update the pull request!
Also we have updated the money section for auditing the code (new service provider found)
Updates
Total funds: Fixed.
full-time equivalent: Fixed.
Table the deliverable of each milestone: It is already included in the details section.

Add VeRocket (formerly ZumoSwap) Application

---

milestone-delivery/deliveries/docs-internationalization-1.md

Docs internationalization milestone 1 completion information

Docs internationalization milestone 1

---

milestone-delivery/deliveries/VeRocket_milestone_1.1.md

Hi,
We have separated M1.1 from M1 and M1.2 submit. Make it independent!

VeRocket Milestone 1.1

---

milestone-delivery/deliveries/VeRocket_milestone_1.2.md
milestone-delivery/deliveries/VeRocket_milestone_1.md

Hi,
We have completed M1 and M1.2 (M1.1 we can send later). 
And we will send an additional email to add more materials on the audit.

Add VeRocket M1 and M1.2 milestone

---

applications/vechain.energy.md

Add application for vechain.energy

---

applications/worldofv.md

WorldOfV - Application Update Feb2022

---

milestone-delivery/README.md

Fix minor typo in README.
applicaiton -> application

Correct minor README.md typo

---

milestone-delivery/deliveries/vechain.energy-M1.md

The development of the first Milestone is completed.
Deliverables were agreed to be proven by hardhat jest unit tests and a Markdown-Document with Code-Snippets. The test report is included in the document, the code-snippets are linked to a website. Test-Deployments are linked as well.
I hope everything is understandable.
Thank you for your support!

Deliver vechain.energy Milestone 1

---

applications/worldofv.md

WoV: update payment address

---

milestone-delivery/deliveries/vechain.energy-M2.md
milestone-delivery/deliveries/vechain.energy-M3.md

The development of the second Milestone is completed.
Deliverables were agreed to be proven by jest unit tests. The test report is included in the document.  The Deployments are linked at the bottom.
I hope everything is understandable.
The development of the third Milestone is completed as well.
Deliverables were agreed to be proven by screenshots and a working web-application. The screenshots are linked in the delivery file. A link to the TestNet-Version is included in the delivery as well.
---
Thank you for your support!

Deliver vechain.energy Milestone 2 + 3

---

applications/thor-devkit-dart.md

Thor-devkit-dart  - Initial Commit

---

README.md
accepted_grant_applications.md

- Update the Mainnet website of vechain.energy
- Add thor-devkit.dart
- Update Grant Committee

Update accepted grant applications and grant committee

---

milestone-delivery/deliveries/VeRocket_milestone_3.md

Hi,
We have completed milestone 3, the Chart of VeRocket.

Milestone 3 of VeRocket

---

milestone-delivery/deliveries/VeRocket_milestone_2.1.md

Hi,
We have completed milestone 2.1, the VTHO distribution of VeUSD event.

Milestone 2.1 of VeRocket

---

milestone-delivery/deliveries/VeRocket_milestone_2.md

VeRocket: add m2 milestone

---

applications/VeBlocks_upgrade.md

Update milestone 3 for higher costs

---

applications/veRocket.md

Thank you VeChain. We have received all grant funds and mark our milestones complete.

mark verocket as complete

---

applications/multi-sig-wallets.md

Add grant application for a multi-sig-application

---

milestone-delivery/deliveries/worldofv-M1.md

Delivery details for Milestone 1

WoV delivery M1

---

milestone-delivery/deliveries/worldofv-M2.md

Delivery details for Milestone 2

WoV delivery M2

---

milestone-delivery/deliveries/worldofv-M3.md

Delivery details for Milestone 3

Wov delivery m3

---

milestone-delivery/deliveries/multi-sig-wallets-M1.md
milestone-delivery/deliveries/multi-sig-wallets-M2.md

A fully integrated Multi-Signature-Wallet was integrated into Sync2 and a Pull Request is available at:  
* https://github.com/vechain/sync2/pull/278
* The Pull-Request also shows a documentation of the application supported by screen recordings
The web deployment was done here:
* https://wallet.vechain.energy
I hope this functionality and add-on for Sync2 will be of good use. Changes and improvements will continue outside of the grants scope.

Add deliveries for Multi-Sig-Wallets M1 + M2

---

applications/dappworld_learning_ecosystem.md

Grant Application - DApp World  

---

milestone-delivery/deliveries/dappworld_learning_ecosystem-milestone-1.md

DApp World Milestone Delivery - 1

---

milestone-delivery/deliveries/node.vechain.energy-M1.md
milestone-delivery/deliveries/node.vechain.energy-M2.md
milestone-delivery/deliveries/node.vechain.energy-M3-M4.md

The milestones for node*vechain.energy were already developed during the past months, the missing deployments have been achieved and configured during the past week.
Please find in this Pull Request the deliveries for the accepted grant in #115 
Thank you again for your support and trust!

Deliver node*vechain.energy

---

applications/mobile-v3-swap.md

added grant application for mobile v3 swap

---

applications/node.vechain.energy.md

Add application for node*vechain.energy

---

applications/miden.md

Stratisnik patch 1 - miden

---

applications/thisismagma.md

Thisismagma

---

applications/vetools_vscode.md

Previous wallet address was recently hacked, so requesting a change to my payment address

VeTools - Update wallet address

---

applications/veFarm.md

VeChain grant proposal - VeFarm

---

Vechain-EasyA-Hackathon-Boston-Oct-2023/applications/FibreTag.md

FibreTag Application

---

Vechain-EasyA-Hackathon-Boston-Oct-2023/applications/movelo.md

Movelo Application for the VeChain x EasyA Harvard Hackathon

Movelo Application VeChain x EasyA Harvard

---

Vechain-EasyA-Hackathon-Boston-Oct-2023/applications/artika_refashion.md

Artika Refashion Application

---

milestone-delivery/deliveries/mobile-v3-swap-milestone-1.md

Mileston 1 of Mobile v3 swap

---

applications/extractor.md

Extractor Grant Application

---

Vechain-EasyA-Hackathon-Boston-Oct-2023/applications/FibreTag.md
Vechain-EasyA-Hackathon-Boston-Oct-2023/milestone-deliveries/fibretag-1.md

- **Initial PR**: https://github.com/vechain/grant-program/pull/195
- **Milestone 1 Deliverable:** https://github.com/jjjutla/grant-program/blob/master/Vechain-EasyA-Hackathon-Boston-Oct-2023/milestone-deliveries/fibretag-1.md

FibreTag - Milestone 1

---

applications/thisismagma.md

Update thisismagma.md typos

---

milestone-delivery/deliveries/thor-devkit-rs-2.md

For more info and testing instructions, check out #224 comments.

Delivery of thor-devkit.rs: 2/3

---

milestone-delivery/deliveries/thor-devkit-rs-1.md

First two milestones of tho-devkit are ready for review. Unfortunately, after first milestone I found out that the library looks too raw to delivered on its own, so decided to wait intil two milestones are completed. Now it is more mature. 
To test the library locally, you will need rust toolchain installed - [this documentation page](https://www.rust-lang.org/tools/install) should help you get started. You will need Rust 1.67.1 or above to compile and run. 
To execute tests (most of them located in the `tests/` folder), run
```
cargo test --all-features
```
To run examples that show some library features:
```
cargo run --example <example_name>`
```
To run the comprehensive example with transaction broadcasting, you'll need two testnet accounts (recipient and sender). Pass two …

Delivery of thor-devkit.rs: 1/3

---

applications/thisismagma.md
milestone-delivery/deliveries/thisismagma_milestone_1.md
milestone-delivery/deliveries/thisismagma_milestone_2.md
milestone-delivery/deliveries/thisismagma_milestone_3.md

thisismagma milestone update

---

applications/oracle.vechain.energy.md

Add Oracle for VET/USD + VTHO/USD Pricing

---

Vechain-EasyA-Hackathon-Boston-Oct-2023/milestone-deliveries/fibretag-2.md

- **Initial PR**: https://github.com/vechain/grant-program/pull/195
- **Milestone 2 Deliverable:** https://github.com/jjjutla/FibreTag/blob/main/fibretag-milestone_2.md

FibreTag - Milestone 2 Completed

---

applications/miden.md

The wallet address has been updated on the application. The one previously used has been compromised. Important: Please update your records accordingly.
- [Y ] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ Y] An Ethereum address for the payment of the milestones is provided inside the application.  
- [ Y] The total funding amount of the project is up to USD $30k for every grant applications.
- [ Y] The initial PR contains only one commit (squash if needed before submitting your PR).

Update miden.md - wallet address

---

applications/miden.md

Reordered the sequence of the milestones as recommended by Vechain1, miden-5.md (PR #248)
- [ Y] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ Y] An Ethereum address for the payment of the milestones is provided inside the application.  
- [ Y] The total funding amount of the project is up to USD $30k for every grant applications.
- [ Y] The initial PR contains only one commit (squash if needed before submitting your PR).

Update miden.md - reordered sequence of milestones

---

applications/extractor.md
milestone-delivery/deliveries/extractor-M1.md
milestone-delivery/deliveries/extractor-M2.md
milestone-delivery/deliveries/extractor-M3.md

Grant Extractor (M1, M2 and M3 deliverables)

---

milestone-delivery/deliveries/milestone-delivery/deliveries/miden-2.md
milestone-delivery/deliveries/milestone-delivery/deliveries/miden-5.md

Submission of 5th delivery
- [ Y] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ Y] An Ethereum address for the payment of the milestones is provided inside the application.  
- [ Y] The total funding amount of the project is up to USD $30k for every grant applications.
- [Y ] The initial PR contains only one commit (squash if needed before submitting your PR).

Miden M2 delivery
